### ISSUE TITLE
File Uploaded using SDK throws 403 

### ISSUE THREAD

**Issue by james-martin-jd** [solid/acl-check#26] opened 2019-06-18 14:13 UTC
## Please describe what you did in reproducible steps
1. Log into an SDK generated application (for example https://develop.generator.inrupt.com)
2. Click on the file uploader, which is represented by the profile image. 
3. Upload a new file/image
4. Observe a 403 error on the PUT request

## How did it work with 4.x series servers?
The file was uploaded properly, and our liveupdates triggered, refreshing the image displayed to the new image

## What happened when you tried the same with the 5.x series server?
A 403 error is observed. The error said that I do not have permission to access the newly uploaded file.

## Any material that will help, logs, error messages, etc.
Request URL: https://jmartin.inrupt.net/profile/_1560867172000_.jpeg
Request Method: PUT
Status Code: 403 Origin Unauthorized
No permission to access this resource
You are currently logged in as https://jmartin.inrupt.net/profile/card#me, but do not have permission to access https://jmartin.inrupt.net/profile/_1560865124000_.jpeg.

**Comment by michielbdejong** [comment] 2019-06-21 14:43
Ah wow, duplicate of #24 even.

**Closed by michielbdejong** 2019-06-21 14:43 UTC
Labels: bug
